"use client";
import {useEffect,useRef,useState} from 'react';
import {Upload,Sparkles,Settings2,ImagePlus,Layers3,Download,RefreshCw,Plus,Pause,Check} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Progress} from '@/components/ui/progress';
import {makeZip} from '@/lib/zip';
import {GEMINI_MODELS,DOUBAO_MODEL} from '@/lib/image-providers';
type Ref={id:string;name:string;url:string};
type Job={id:string;position:number;prompt:string;status:string;image:string|null;error:string|null};
type Collection={id:string;name:string;config:{refs:string[];style:string;ratio:string;extra:string;mode:string};jobs:Job[]};
async function api(path:string,method='GET',value?:unknown){const r=await fetch('/api/studio/'+path,{method,headers:value instanceof FormData?{}:value===undefined?{}:{'Content-Type':'application/json'},body:value===undefined?undefined:value instanceof FormData?value:JSON.stringify(value)});let data:any;try{data=await r.json()}catch{throw new Error('服务响应异常，请稍后重试')}if(!r.ok)throw Object.assign(new Error(data.error||'请求失败'),{code:data.code,retryAfter:data.retryAfter,stopQueue:data.stopQueue});return data}
function Choice({value,onChange,items}:{value:string;onChange:(s:string)=>void;items:string[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="w-full h-11"><SelectValue/></SelectTrigger><SelectContent>{items.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select>}
async function prepareFile(file:File){if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('请选择 JPG、PNG 或 WebP 图片');if(file.size>40000000)throw new Error('单张原图超过 40 MB，请先缩小图片');const bmp=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bmp.width,bmp.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bmp.width*scale);canvas.height=Math.round(bmp.height*scale);const ctx=canvas.getContext('2d');if(!ctx)throw new Error('浏览器不支持图片处理');ctx.drawImage(bmp,0,0,canvas.width,canvas.height);bmp.close();const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('图片读取失败')),'image/webp',.9));if(blob.size>2000000)throw new Error('图片细节过多，请缩小图片后重试');return new File([blob],file.name.replace(/\.[^.]+$/,'')+'.webp',{type:'image/webp'})}
export default function Home(){
const [style,setStyle]=useState('明亮暖调侘寂'),[ratio,setRatio]=useState('3:4'),[count,setCount]=useState(10),[name,setName]=useState(''),[extra,setExtra]=useState(''),[mode,setMode]=useState('不同场景系列');
const [refs,setRefs]=useState<Ref[]>([]),[collection,setCollection]=useState<Collection|null>(null),[history,setHistory]=useState<any[]>([]);
const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[running,setRunning]=useState(false);
const [settings,setSettings]=useState(false),[configured,setConfigured]=useState(false),[model,setModel]=useState('gemini-3.1-flash-image'),[models,setModels]=useState(['gemini-3.1-flash-image','gemini-3-pro-image']),[key,setKey]=useState(''),[preview,setPreview]=useState<string|null>(null);
const [provider,setProvider]=useState('gemini'),[activeProvider,setActiveProvider]=useState('gemini'),[providerStates,setProviderStates]=useState<Record<string,{configured:boolean;model:string}>>({gemini:{configured:false,model:GEMINI_MODELS[0]},doubao:{configured:false,model:DOUBAO_MODEL}});
const stop=useRef(false),active=useRef(false),latest=useRef(collection);latest.current=collection;
async function initialize(){try{const [s,h]=await Promise.all([api('settings'),api('collections')]);setConfigured(s.configured);setModel(s.model);setModels(s.models);setProvider(s.provider);setActiveProvider(s.provider);setProviderStates(s.providers);setHistory(h)}catch(e){setError((e as Error).message)}}
useEffect(()=>{initialize()},[]);
async function load(id:string){const c=await api('collections/'+id);setCollection(c);return c as Collection}
async function upload(files:FileList|File[]|null){if(!files||uploading)return;setUploading(true);setError('');let n=0;try{for(const file of Array.from(files)){const f=await prepareFile(file);const form=new FormData();form.append('file',f);const result=await api('assets','POST',form);setRefs(old=>[...old,result]);n++}setMessage('已保存 '+n+' 张参考图')}catch(e){setError((e as Error).message)}finally{setUploading(false)}}
async function create(){if(!refs.length){setError('请至少上传一张产品图');return}setBusy(true);setError('');try{const c=await api('collections','POST',{refs:refs.map(r=>r.id),style,ratio,count,name,extra,mode:mode==='同一场景变化'?'variations':'series'});await load(c.id);await initialize();setMessage('场景已编排，可以逐张修改描述后开始生成。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function saveSettings(){setBusy(true);setError('');try{await api('settings','POST',{key,model,provider});setKey('');await initialize();setSettings(false);setMessage('API 配置已加密保存，首次生成将验证密钥和模型权限。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function removeKey(){setBusy(true);try{await api('settings','DELETE',{provider});setKey('');await initialize();setSettings(false);setMessage('已移除所选服务商的密钥，其他服务商配置保留。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function savePrompt(job:Job){await api('jobs/'+job.id,'PATCH',{prompt:job.prompt})}
async function run(jobs:Job[],sample=false,redo=false){if(active.current||!collection)return;if(!configured){setSettings(true);return}const cid=collection.id;active.current=true;stop.current=false;setRunning(true);setError('');setMessage('生成期间请保持页面打开。暂停或关闭后，已完成的图片仍会保留。');let cursor=0;let failed=0;
async function worker(){while(!stop.current&&cursor<jobs.length){const j=jobs[cursor++];try{await savePrompt(j);setCollection(c=>c?{...c,jobs:c.jobs.map(x=>x.id===j.id?{...x,status:'running',error:null}:x)}:c);await api('generate/'+j.id,'POST',{sample,redo})}catch(e){failed++;stop.current=true;setError((e as Error).message)}finally{try{await load(cid)}catch{setError('连接中断，稍后可从历史系列恢复')}}}}
try{await worker();setMessage(failed?'遇到错误，队列已暂停。未提交的场景保留，解决问题后可继续。':stop.current?'已暂停。当前已提交的图片已处理，可继续生成。':'本轮图片已生成并保存。')}finally{active.current=false;setRunning(false);await initialize()}}
async function downloadAll(){if(!collection)return;setBusy(true);setError('');try{const files=[];for(const j of collection.jobs.filter(j=>j.image)){const r=await fetch('/api/studio/assets/'+j.image);if(!r.ok)throw new Error('图片下载失败');const mime=r.headers.get('content-type');files.push({name:collection.name+'-'+String(j.position+1).padStart(2,'0')+(mime?.includes('jpeg')?'.jpg':mime?.includes('webp')?'.webp':'.png'),data:new Uint8Array(await r.arrayBuffer())})}const blob=makeZip(files);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=collection.name+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const abort=new AbortController();Promise.resolve(mc.registerTool({name:'read_generation_progress',description:'读取当前商品图片系列的生成进度，不启动生成。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input:any){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('不接受参数');const c=latest.current;return c?{name:c.name,jobs:c.jobs.map(j=>({position:j.position+1,status:j.status}))}:{collection:null}}},{signal:abort.signal})).catch(()=>{});return ()=>abort.abort()},[]);
const done=collection?.jobs.filter(j=>j.status==='done').length||0;const remaining=collection?.jobs.filter(j=>j.status==='pending'||j.status==='failed')||[];
return <main><header><a className="brand" href="/"><span className="brandicon"><Layers3 size={23}/></span>造景<span className="brandcaption">商品影像工作室</span></a><button className="ghost" disabled={running} onClick={()=>{setKey('');setSettings(true)}}><Settings2 size={17}/>{configured?(activeProvider==='doubao'?'豆包 · 2K':'Gemini · 2K'):'配置 API'}</button></header><div className="workspace"><aside className="controls"><div className="eyebrow">NEW COLLECTION / 新建系列</div><h1>让产品，走进好场景。</h1><p className="muted">一张产品图，开始一整套创作。</p><section><h2><b>01</b> 产品参考</h2><label className="upload" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();upload(e.dataTransfer.files)}}><Upload/><strong>{uploading?'正在保存图片…':'点击或拖入产品图片'}</strong><span>至少 1 张 · 支持持续追加</span><input disabled={uploading} type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={e=>{upload(e.target.files);e.target.value=''}}/></label><div className="refs">{refs.map((r,i)=><div key={r.id} className="ref"><img src={r.url} alt={r.name}/><button onClick={()=>setRefs(old=>[r,...old.filter(x=>x.id!==r.id)])}>{i===0?'主参考图':'设为主图'}</button><button onClick={()=>setRefs(old=>old.filter(x=>x.id!==r.id))} aria-label={'移除'+r.name}>移除</button></div>)}</div><p className="hint">每个系列对应一款产品。图片会自动缩小后上传；每张出图使用主图及最多 3 张补充参考，轮流选用。</p><label className="field">产品名称（选填）<input value={name} onChange={e=>setName(e.target.value)} placeholder="例如：樱花刺绣桌布" maxLength={100}/></label></section>
<section><h2><b>02</b> 画面风格</h2><RadioGroup value={style} onValueChange={setStyle} className="styles">{['明亮暖调侘寂','波西米亚','可爱清新','北欧简约','现代高级','自定义'].map((s,i)=><label className={'style '+(style===s?'chosen':'')} key={s}><RadioGroupItem value={s} className="sr-only"/><span className={'swatch swatch'+i}/>{s}</label>)}</RadioGroup><label className="field">补充要求<textarea value={extra} onChange={e=>setExtra(e.target.value)} maxLength={3000} placeholder="例如：浅粉樱花、柔和日光，保留产品原本颜色"/></label></section>
<section><h2><b>03</b> 生成设置 <span className="badge">2K</span></h2><div className="two"><label className="field">图片比例<Choice value={ratio} onChange={setRatio} items={['3:4','1:1','4:5','9:16','16:9']}/></label><label className="field">生成张数<input type="number" min={1} max={100} value={count} onChange={e=>setCount(Number(e.target.value))}/></label></div><label className="field">场景模式<Choice value={mode} onChange={setMode} items={['不同场景系列','同一场景变化']}/></label></section><button className="primary wide" disabled={busy||running||uploading} onClick={create}><Sparkles size={18}/>{busy?'处理中…':'编排拍摄场景'}</button><p className="hint">先保存并编辑场景，再决定是否调用 API。默认输出 2K。生成图片会消耗所选服务商的 API 额度。</p></aside>
<article className="canvas"><div className="canvashead"><div><div className="eyebrow">YOUR CREATIVE SPACE</div><h2>{collection?.name||'场景与作品'}</h2></div><span className="badge">{collection?.config.ratio||ratio} · {collection?.config.style||style}</span></div>
{error&&<div role="alert" className="notice error">{error}</div>}{message&&<div role="status" className="notice">{message}</div>}
{history.length>0&&<details><summary className="muted">历史系列 · 最近 {history.length} 个</summary><div className="history">{history.map(h=><button className="ghost" key={h.id} disabled={running} onClick={()=>load(h.id).catch(e=>setError(e.message))}>{h.name} · {new Date(h.created).toLocaleDateString('zh-CN')}</button>)}</div></details>}
{!collection?<div className="emptycanvas"><div className="emptyicon"><ImagePlus size={42} strokeWidth={1}/></div><h3>下一套作品，从这里开始</h3><p>上传产品，选好风格。<br/>先编辑场景，再生成样图或整套作品。</p><div className="steps"><span>01 上传产品</span><span>02 编排场景</span><span>03 生成作品</span></div></div>:<>
<div className="toolbar"><button className="ghost" disabled={running} onClick={()=>{setRefs(collection.config.refs.map(id=>({id,name:collection.name,url:"/api/studio/assets/"+id})));setName(collection.name);setStyle(collection.config.style);setRatio(collection.config.ratio);setExtra(collection.config.extra);setMessage("已带入此产品和风格，可在左侧调整并新建系列。")}}><Plus size={16}/>沿用产品</button><button className="primary" disabled={running||busy||collection.jobs[0]?.status==='running'} onClick={()=>run([collection.jobs[0]],false,!!collection.jobs[0].image)}><Sparkles size={16}/>{collection.jobs[0]?.image?'重做第一张样图':'先生成一张样图'}</button><button className="ghost" disabled={running||busy||!remaining.length} onClick={()=>run(remaining,collection.jobs[0]?.status==='done')}><Layers3 size={16}/>{collection.jobs[0]?.status==='done'?'认可样图，生成剩余':'直接生成全部'}（{remaining.length}）</button>{running&&<button className="ghost" onClick={()=>{stop.current=true;setMessage('正在暂停，当前已提交的请求会继续完成。')}}><Pause size={16}/>暂停队列</button>}<button className="ghost" disabled={busy||!collection.jobs.some(j=>j.image)} onClick={downloadAll}><Download size={16}/>打包下载</button><button className="ghost" disabled={running} onClick={()=>load(collection.id).catch(e=>setError(e.message))}><RefreshCw size={16}/>刷新状态</button></div>
<div className="progressrow"><Progress value={done/collection.jobs.length*100}/><span>{done} / {collection.jobs.length} 已完成</span></div><div className="grid">{collection.jobs.map(j=><div className="scene" key={j.id}>{j.image&&<button className="imagebutton" onClick={()=>setPreview('/api/studio/assets/'+j.image)}><img style={{aspectRatio:collection.config.ratio.replace(':','/')}} src={'/api/studio/assets/'+j.image} alt={'场景 '+(j.position+1)}/></button>}<div className="scenecontent"><h3><span className="number">{String(j.position+1).padStart(2,'0')}</span> {j.prompt.split('\n')[0]}</h3><textarea aria-label={'场景 '+(j.position+1)+' 描述'} value={j.prompt} disabled={running||j.status==='running'} onChange={e=>setCollection(c=>c?{...c,jobs:c.jobs.map(x=>x.id===j.id?{...x,prompt:e.target.value}:x)}:c)} onBlur={()=>savePrompt(j).catch(e=>setError(e.message))}/><div className="scenestatus" aria-live="polite">{j.status==='done'?'✓ 已保存':j.status==='running'?'正在生成…':j.status==='failed'?'生成失败':'等待生成'}</div>{j.error&&<p className="hint error">{j.error}</p>}<div className="sceneactions"><button className="ghost" disabled={running||busy||j.status==='running'} onClick={()=>run([j],false,!!j.image)}><RefreshCw size={14}/>{j.image?'重新生成':'生成这张'}</button>{j.image&&<a className="download" href={'/api/studio/assets/'+j.image+'?download=1'}>下载</a>}</div></div></div>)}</div></>}
<footer>产品始终是主角。生成后请检查花纹、颜色与结构是否准确。</footer></article></div>
<Dialog open={settings} onOpenChange={setSettings}><DialogContent className="settings"><DialogHeader><DialogTitle>模型与 API 设置</DialogTitle><DialogDescription>密钥在服务端加密保存，不会放入浏览器存储。Gemini 和豆包分别保存密钥，切换时不会覆盖另一份配置。</DialogDescription></DialogHeader>{error&&<div role="alert" className="notice error">{error}</div>}<label className="field">生图服务商<Choice value={provider==='gemini'?'Google Gemini':'豆包 · 火山方舟'} onChange={value=>{const next=value==='Google Gemini'?'gemini':'doubao';setProvider(next);setKey('');setError('');setModel(providerStates[next].model);setModels(next==='gemini'?GEMINI_MODELS:[DOUBAO_MODEL])}} items={['Google Gemini','豆包 · 火山方舟']}/></label><label className="field">{provider==='gemini'?'Gemini API 密钥':'火山方舟 API 密钥'}<input type="password" autoComplete="new-password" value={key} onChange={e=>setKey(e.target.value)} placeholder={providerStates[provider].configured?'已保存，留空保留原密钥':'粘贴所选服务商的 API Key'}/></label><label className="field">图片模型<Choice value={model} onChange={setModel} items={models}/></label>{provider==='doubao'?<p className="hint">Doubao-Seedream-5.0-pro · 火山方舟官方接口。需要单独开通此模型并配置火山方舟密钥。</p>:<p className="hint">gemini-3.8-flash 仅支持理解图片，不支持生成图片，因此此处使用 Image 系列模型。</p>}<p className="hint">默认生成 2K 图片，每次处理一张。遇到限流按服务商建议等待；仍然失败时暂停队列。费用与配额以所选服务商为准。</p><a className="download" href={provider==='gemini'?'https://aistudio.google.com/apikey':'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey'} target="_blank" rel="noreferrer">{provider==='gemini'?'前往 Google AI Studio 获取密钥':'前往火山方舟获取密钥'}</a>{provider==='gemini'&&<a className="download" href="https://aistudio.google.com/usage" target="_blank" rel="noreferrer">查看 Google 用量与配额</a>}<button className="primary" disabled={busy} onClick={saveSettings}>{busy?'保存中…':'保存配置'}</button>{providerStates[provider].configured&&<button className="ghost" disabled={busy} onClick={removeKey}>移除已保存的密钥</button>}</DialogContent></Dialog>
<Dialog open={!!preview} onOpenChange={()=>setPreview(null)}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>图片预览</DialogTitle><DialogDescription>检查产品细节后再下载使用。</DialogDescription></DialogHeader>{preview&&<img className="previewimage" src={preview} alt="生成图片大图"/>}</DialogContent></Dialog>
</main>}