import {GEMINI_MODELS,DOUBAO_MODEL,RESOLUTION,generateImage,ProviderError} from '@/lib/image-providers';
import {bucket,db,user,reply,body,text,HttpError,config,cipher,ownedAsset,encode} from '@/lib/studio-server';
import {styles,makeScenes} from '@/lib/templates';
export const dynamic='force-dynamic';
type Job={id:string;collection_id:string;owner:string;position:number;prompt:string;status:string;image:string|null;error:string|null;started:number|null;attempt:string|null};
async function handle(req:Request,ctx:{params:Promise<{path:string[]}>}){
try{
const owner=user(req);const {path}=await ctx.params;const [action,id]=path;const method=req.method;
if(action==='settings'){
if(method==='GET'){const c=await config(owner);const provider=c?.provider||'gemini';return reply({provider,configured:provider==='gemini'?!!c?.secret:!!c?.doubao_secret,model:provider==='gemini'?(c?.model||GEMINI_MODELS[0]):(c?.doubao_model||DOUBAO_MODEL),models:provider==='gemini'?GEMINI_MODELS:[DOUBAO_MODEL],providers:{gemini:{configured:!!c?.secret,model:c?.model||GEMINI_MODELS[0]},doubao:{configured:!!c?.doubao_secret,model:c?.doubao_model||DOUBAO_MODEL}},resolution:RESOLUTION})}
if(method==='DELETE'){const b=await body(req);const provider=b.provider||'gemini';if(!['gemini','doubao'].includes(provider))throw new HttpError(400,'服务商不正确');await db().prepare(provider==='gemini'?"UPDATE settings SET secret='' WHERE owner=?":"UPDATE settings SET doubao_secret=NULL WHERE owner=?").bind(owner).run();return reply({ok:true})}
if(method==='POST'){
const b=await body(req);const provider=b.provider||'gemini';if(!['gemini','doubao'].includes(provider))throw new HttpError(400,'服务商不正确');
const model=text(b.model,100);const supported=provider==='gemini'?GEMINI_MODELS:[DOUBAO_MODEL];if(!supported.includes(model))throw new HttpError(400,model==='gemini-3.8-flash'?'Gemini 3.8 Flash 不支持生图，请选择 Image 模型。':'请选择支持的图片模型');
const key=text(b.key||'',300).trim();const c=await config(owner);const existing=provider==='gemini'?c?.secret:c?.doubao_secret;const secret=key?await cipher(key):existing;if(!secret)throw new HttpError(400,'请输入所选服务商的 API 密钥');
if(provider==='gemini')await db().prepare("INSERT INTO settings(owner,secret,model,provider) VALUES(?,?,?,'gemini') ON CONFLICT(owner) DO UPDATE SET secret=excluded.secret,model=excluded.model,provider='gemini'").bind(owner,secret,model).run();
else await db().prepare("INSERT INTO settings(owner,secret,model,provider,doubao_secret,doubao_model) VALUES(?,'',?,'doubao',?,?) ON CONFLICT(owner) DO UPDATE SET doubao_secret=excluded.doubao_secret,doubao_model=excluded.doubao_model,provider='doubao'").bind(owner,GEMINI_MODELS[0],secret,model).run();
return reply({ok:true})}
}
if(action==='assets' && method==='POST'){
const size=Number(req.headers.get('content-length')||0);if(size>2500000)throw new HttpError(413,'单张上传文件需小于 2 MB');
const form=await req.formData();const f=form.get('file');if(!(f instanceof File)||f.size>2000000||f.size===0)throw new HttpError(400,'请选择小于 2 MB 的图片');if(!['image/jpeg','image/png','image/webp'].includes(f.type))throw new HttpError(400,'支持 JPG、PNG 和 WebP 图片');
const data=new Uint8Array(await f.arrayBuffer());const signature=(f.type==='image/jpeg'&&data[0]===255&&data[1]===216)||(f.type==='image/png'&&data[0]===137&&data[1]===80&&data[2]===78&&data[3]===71)||(f.type==='image/webp'&&String.fromCharCode(...data.slice(0,4))==='RIFF'&&String.fromCharCode(...data.slice(8,12))==='WEBP');if(!signature)throw new HttpError(400,'图片格式与内容不一致');
const aid=crypto.randomUUID();await bucket().put(aid,data,{httpMetadata:{contentType:f.type}});await db().prepare('INSERT INTO assets(id,owner,name,mime,created) VALUES(?,?,?,?,?)').bind(aid,owner,f.name.slice(0,200),f.type,Date.now()).run();return reply({id:aid,name:f.name,url:'/api/studio/assets/'+aid});
}
if(action==='assets' && id && method==='GET'){const a=await ownedAsset(id,owner);const obj=await bucket().get(id);if(!obj)throw new HttpError(404,'文件不存在');return new Response(obj.body,{headers:{'Content-Type':a.mime,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff',...(new URL(req.url).searchParams.has('download')?{'Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(a.name)}:{})}})}
if(action==='collections'&&method==='GET'){
if(id){const c=await db().prepare('SELECT * FROM collections WHERE id=? AND owner=?').bind(id,owner).first<any>();if(!c)throw new HttpError(404,'系列不存在');await db().prepare("UPDATE jobs SET status='failed',error='上次请求已中断或超时。请确认后手动重试。' WHERE collection_id=? AND owner=? AND status='running' AND started<?").bind(id,owner,Date.now()-600000).run();const jobs=await db().prepare('SELECT * FROM jobs WHERE collection_id=? AND owner=? ORDER BY position').bind(id,owner).all();return reply({...c,config:JSON.parse(c.config),jobs:jobs.results})}
await db().prepare("UPDATE jobs SET status='failed',error='上次请求已中断或超时，请手动重试。' WHERE owner=? AND status='running' AND started<?").bind(owner,Date.now()-600000).run();const c=await db().prepare('SELECT id,name,created FROM collections WHERE owner=? ORDER BY created DESC LIMIT 100').bind(owner).all();return reply(c.results)}
if(action==='collections'&&method==='POST'){
const b=await body(req);const count=Number(b.count);if(!Number.isInteger(count)||count<1||count>100)throw new HttpError(400,'每个系列可生成 1–100 张，更多图片可分系列生成');if(!Array.isArray(b.refs)||!b.refs.length)throw new HttpError(400,'请至少上传一张产品图');const refs=[...new Set(b.refs.map((v:unknown)=>text(v,50)))];for(const rid of refs)await ownedAsset(String(rid),owner);
const name=text(b.name||'未命名产品',100),style=text(b.style,100),extra=text(b.extra||'',3000),ratio=text(b.ratio,10);if(!Object.keys(styles).includes(style)||!['3:4','1:1','4:5','9:16','16:9'].includes(ratio))throw new HttpError(400,'风格或比例不正确');
const mode=b.mode==='variations'?'variations':'series';const cid=crypto.randomUUID();const cfg={refs,name,style,extra,ratio,mode};const prompts=makeScenes(count,name,mode);
await db().batch([db().prepare('INSERT INTO collections(id,owner,name,config,created) VALUES(?,?,?,?,?)').bind(cid,owner,name,JSON.stringify(cfg),Date.now()),...prompts.map((p,i)=>db().prepare('INSERT INTO jobs(id,collection_id,owner,position,prompt,status) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),cid,owner,i,p,'pending'))]);return reply({id:cid})}
if(action==='jobs'&&id&&method==='PATCH'){const b=await body(req);const prompt=text(b.prompt,6000);const r=await db().prepare("UPDATE jobs SET prompt=? WHERE id=? AND owner=? AND status!='running'").bind(prompt,id,owner).run();if(!r.meta.changes)throw new HttpError(409,'该图片正在生成，暂时不能修改');return reply({ok:true})}
if(action==='generate'&&id&&method==='POST'){
const c=await config(owner);const provider=c?.provider||'gemini';const secret=provider==='gemini'?c?.secret:c?.doubao_secret;if(!c||!secret)throw new HttpError(400,'请先在 API 设置中保存所选服务商的密钥','MISSING_KEY',0,true);const cooldown=provider==='gemini'?c.gemini_cooldown:c.doubao_cooldown;if(cooldown>Date.now())throw new HttpError(429,'正在等待服务商限流冷却，请 '+Math.ceil((cooldown-Date.now())/1000)+' 秒后继续。','RATE_LIMIT',Math.ceil((cooldown-Date.now())/1000),true);const model=provider==='gemini'?c.model:c.doubao_model;
const job=await db().prepare('SELECT * FROM jobs WHERE id=? AND owner=?').bind(id,owner).first<Job>();if(!job)throw new HttpError(404,'任务不存在');
const b=await body(req);if(job.status==='done'&&!b.redo)return reply({ok:true});
const collection=await db().prepare('SELECT * FROM collections WHERE id=? AND owner=?').bind(job.collection_id,owner).first<any>();if(!collection)throw new HttpError(404,'系列不存在');
const cfg=JSON.parse(collection.config);const attempt=crypto.randomUUID();const claim=await db().prepare("UPDATE jobs SET status='running',error=NULL,started=?,attempt=? WHERE id=? AND owner=? AND status!='running' AND (SELECT COUNT(*) FROM jobs WHERE owner=? AND status='running')<1").bind(Date.now(),attempt,id,owner,owner).run();if(!claim.meta.changes)throw new HttpError(409,'已有任务正在运行，请稍后再试','BUSY',0,true);
try{
const selected:string[]=[cfg.refs[0]];const rest=cfg.refs.slice(1);for(let i=0;i<Math.min(3,rest.length);i++)selected.push(rest[(job.position*3+i)%rest.length]);
const parts:any[]=[];for(const rid of selected){const a=await ownedAsset(rid,owner);const obj=await bucket().get(rid);if(!obj)throw new Error('参考图片读取失败，请重新上传');parts.push({inlineData:{mimeType:a.mime,data:encode(await obj.arrayBuffer())}})}
if(b.sample){const sample=await db().prepare("SELECT image FROM jobs WHERE collection_id=? AND owner=? AND position=0 AND status='done'").bind(job.collection_id,owner).first<{image:string}>();if(sample?.image&&sample.image!==job.image){const a=await ownedAsset(sample.image,owner);const obj=await bucket().get(a.id);if(obj){parts.push({text:'以下额外图片仅作为已确认的光线和整体风格参考，产品细节仍以原始参考图为准。'});parts.push({inlineData:{mimeType:a.mime,data:encode(await obj.arrayBuffer())}})}}}
parts.push({text:'请实际生成一张独立的写实商品展示图片，不要拼图，不要文字说明，不添加宣传文字或可见水印。产品：'+cfg.name+'。严格保持原始参考图中产品的颜色、形状、比例、图案、标识和可见工艺，不虚构未展示的结构。产品是视觉主体，道具少且不遮挡。根据该产品实际用途自然摆放，若是桌布则真实铺设垂落，若是窗帘则自然悬挂。只改变场景和拍摄方式。风格：'+styles[cfg.style]+'。用户补充：'+cfg.extra+'。当前场景：'+job.prompt+'。图片比例：'+cfg.ratio+'。'});
const key=await cipher(secret,true);const output=await generateImage(provider,model,key,parts,cfg.ratio);const bytes=Buffer.from(output.data,'base64');const mime=output.mimeType;if(!['image/png','image/jpeg','image/webp'].includes(mime)||bytes.length>20000000)throw new Error('生成图片格式或大小不受支持');
const aid=crypto.randomUUID();const filename=cfg.name+'-'+String(job.position+1).padStart(2,'0')+(mime==='image/jpeg'?'.jpg':mime==='image/webp'?'.webp':'.png');await bucket().put(aid,bytes,{httpMetadata:{contentType:mime}});
await db().batch([db().prepare('INSERT INTO assets(id,owner,name,mime,created) VALUES(?,?,?,?,?)').bind(aid,owner,filename,mime,Date.now()),db().prepare("UPDATE jobs SET image=?,status='done',error=NULL WHERE id=? AND owner=? AND attempt=?").bind(aid,id,owner,attempt)]);return reply({ok:true,image:aid,provider,model,resolution:RESOLUTION});
 }catch(e){if(e instanceof ProviderError && e.retryAfter){await db().prepare(provider==='gemini'?'UPDATE settings SET gemini_cooldown=? WHERE owner=?':'UPDATE settings SET doubao_cooldown=? WHERE owner=?').bind(Date.now()+e.retryAfter*1000,owner).run()}const message=e instanceof Error?(e.name==='TimeoutError'?'请求超时，请稍后手动重试。':e.message):'生成失败';await db().prepare("UPDATE jobs SET status='failed',error=? WHERE id=? AND owner=? AND attempt=?").bind(message,id,owner,attempt).run();throw new HttpError(e instanceof ProviderError?e.status:502,message,e instanceof ProviderError?e.code:'GENERATION_FAILED',e instanceof ProviderError?e.retryAfter:0,true)}
}
throw new HttpError(404,'找不到该操作');
}catch(e){if(!(e instanceof HttpError))console.error('Studio operation failed',e instanceof Error?e.message:'unknown');return reply({error:e instanceof HttpError?e.message:'服务暂时不可用，请稍后重试。',code:e instanceof HttpError?e.code:'SERVER_ERROR',retryAfter:e instanceof HttpError?e.retryAfter:0,stopQueue:e instanceof HttpError?e.stopQueue:true},e instanceof HttpError?e.status:500)}
}
export const GET=handle;export const POST=handle;export const PATCH=handle;export const DELETE=handle;
